name: web-wasm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build with wasm-pack
        run: |
          cd crates/game
          wasm-pack build --target web --out-dir ../../web/dist --no-typescript
          ls -la ../../web/dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
  
  deploy-preview:
    if: github.event_name == 'pull_request'
    needs: build-wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: web/dist
      - name: Deploy to preview
        run: echo "Preview deployment ready"
